# All possible configurations for the Alexa Skills Kit
# or Alexa app or whatever data regarding to Alexa goes here.
#
# You can access these data later on in the app through +ALEXA_CONFIG+ constant.
# See config/initializers/alexa_config.rb
#
defaults: &defaults
  SKILLS_IDS:
    # List your skills and their applicationIDs as key/value pairs.
    # See app/helpers/alexa/request/validators/skill_validator.rb for details.
    RubyLabsLLC: 'amzn1.ask.skill.b748b170-e423-4557-bab6-a9d93d1ef947'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
